name: 'Requirement_test_unit_test'
description: 'Requirement test logs validation unit_test'
inputs:
  input-files:  # id of input
    description: 'input folder requirement file'
    required: true
    default: 'tests/requirement_test/'
runs:
  using: "composite"
  steps:
    - run: python -m pip install PyGithub  # Installing dependencies
      shell: bash
    - run: python ${{ github.action_path }}/test_lib/xml_format_checker.py  ${{ inputs.input-files }}
      shell: bash
    - run: python ${{ github.action_path }}/test_lib/validate_xml.py -i ${{ inputs.input-files }} -s ${{ github.action_path }}/test_lib/schema.xsd
      shell: bash
    - run: python ${{ github.action_path }}/test_lib/test_cim.py -i ${{ inputs.input-files }} -j ${{ github.action_path }}/test_lib/sa-commoninformationmodel/models/
      shell: bash
    - name: Upload test format output file
      uses: actions/upload-artifact@v2
      with:
        name: upload-test-format
        path: test_format_output.txt